### ISSUE TITLE
채팅 데이터 비공개 처리

### ISSUE THREAD

**Issue by rishubil** [2channelkrt/twitch-highlight-predictor#1]
제 닉네임을 검색해보다가 우연히 이 레포가 나와서 깜짝 놀랐습니다. 

아무래도 실제 트위치 채팅을 수집하여 샘플 데이터로 사용하신 것 같은데,
채팅 데이터를 비공개처리해주실 수 있나요?

**Comment by 2channelkrt** [comment]
안녕하세요, 해당 부분에 대해 신경쓰지 못한 점 죄송합니다. 곧 데이터 부분을 비공개처리 하도록 하겠습니다.

**Comment by 2channelkrt** [comment]
챗 로그 데이터를 암호화 했습니다. 문의주셔서 감사합니다.
